### ISSUE TITLE
SQ 1.5.11 Compatible?

### ISSUE THREAD

**Issue by ATCUSER1** [bitfocus/companion-module-allenheath-sq#66]
Is SQ firmware 1.5.11 compatible? Devices are connecting (SQ Mix app working fine on same devices) but nothing is being sent via companion - buttons not working, variables not displaying - despite connection (green tick) established in Connections page. Tried on devices running companion v3.1.0 and v3.4.0

**Comment by jswalden** [comment]
I'm not sure what firmware is on my mixer, but it's definitely 1.5.* firmware, and I can't really imagine A&H accidentally breaking MIDI over TCP (what the Companion module uses to connect -- SQ MixPad and SQ4You use a separate, proprietary connection mechanism) in a minor revision.

It's much likelier your network setup breaks connecting to the mixer.  Have you made sure the computer running Companion allows outgoing connections on port 51325?  If you're running Companion on Linux or a Mac, try opening a terminal and typing this in, replacing `$MIXER_IP` with the actual IP address of a freshly turned on mixer that you haven't tried to connect to:

```bash
printf '\xb0\x00\x00\xc0\x07' | nc $MIXER_IP 51325
```

If your mixer has a scene 8 created on it (with scenes numbered 1-300), this should recall scene 8.  (You can change the `7` in there to any of `0` to `9` to recall scene 1 to 10 if you'd rather test a different scene.)

If this doesn't work, then you're probably not connecting to the mixer, and you should verify your network and firewalls aren't broken and that SQ network settings are correct.  (Or the SQ isn't responding to MIDI scene change messages, but this is very unlikely.)

(This module hasn't had a fresh release since before Companion 3.0.  I'm hoping to have a release ready before 3.5.0, that will consist of a handful of bugfixes but mostly will be an incremental refactor/rewrite into significantly more readable code.)

**Comment by ATCUSER1** [comment]
Thanks for the quick reply. I'm running SQ Firmware 1.5.11. In terminal I ran:

```
nc -zv 10.90.0.47 51325
``` 

and got:

```
Connection to 10.90.0.47 port 51325 [tcp/*] succeeded!
```

When I ran 

```
printf '\xb0\x00\x00\xc0\x07' | nc 10.90.0.47 51325
``` 

Terminal gives no reply or confirmation, terminal simply opens a new command line, and the scene does not change to scene 8 on the SQ7. Not sure where to go from here... I was running firmware 1.5.XX before, and I'd like to roll back to an earlier version of 1.5, but I can't see one available on their [resources](https://www.allen-heath.com/hardware/sq/sq-5/resources/) page.

**Comment by ATCUSER1** [comment]
![Screenshot 2024-09-19 at 14 06 27](https://github.com/user-attachments/assets/697582fe-ac9a-4dab-98d5-1a5b6fb2da56)

**Comment by jswalden** [comment]
Hmm.  That looks like Wireshark, right?  My TCP-fu is not super strong, but [this](https://stackoverflow.com/questions/78046101/is-the-rst-ack-packet-in-wireshark-normal) seems to suggest the mixer is just refusing the TCP connection completely.  (And if you can't open the TCP socket, you can't send MIDI over it.)  _Or_, whatever router you have is denying the packets, or there are IP ACLs on the network switch preventing the connection, or something along the network between your computer and the mixer is interfering.

If simply opening a TCP socket to the mixer is coming up empty, then given that is _necessarily prerequisite_ to everything the Companion module does (it's all just MIDI sent over the TCP connection), the module is SOL here.  If you're sure the firmware update was the only thing that changed -- and that the firmware update didn't reset the network connection settings on the SQ-7?  worth checking those to be sure -- then this seems improbably like an A&H firmware bug.  Otherwise it has to be a firewall/network issue of some sort on your end, seems to me.  Either way, I doubt it's a module bug.

**Comment by ATCUSER1** [comment]
I'm so sorry - it seems I've wasted your time. Long-ish story short, the MIDI channel in the console had been changed without my knowledge. I've set it to 1, and all is in order. 

I owe you several beers!

**Comment by jswalden** [comment]
Happy to hear you've figured it out.

Honestly, I'm surprised the mixer is closing the TCP connection for a MIDI channel mismatch -- I'd have figured it would just ignore the traffic.  Maybe having it flatly close the connection for not matching the MIDI channel (or MIDI control channel) setting is fail-fast, to most quickly detect error?  :shrug:  If I can reproduce this on my mixer, I may look into logging a warning of the possible reason so it's more apparent to future users -- will leave that to a fresh issue if so.
