### ISSUE TITLE
Input/Output Label as a variable in Companion

### ISSUE THREAD

**Issue by Benjamin2509** [bitfocus/companion-module-allenheath-sq#67]
Hi dont know if its already requested, but is there a way to show the Label of an In/Out as a Variable?
Ive noticed that there are Variables for the Level but not for the Channel Name.

And another Request would be is it possible to enter a value like +5db or +10  when sending Fader Channel-Level to a Mix?

Thanks

**Comment by jswalden** [comment]
At least as far as the current SQ documentation goes, it is not possible to access the labels.  (For some other mixer lines, A&H does document how to access the labels.  Maybe how to set them, too -- memory hazy.  But not for the SQ.)

Unless someone decides to reverse-engineer the SQ MixPad API, and then make ongoing effort in keeping an implementation in Companion working (akin to how A&H say you have to sync mixer firmware versions with MixPad versions, so plainly internally they don't have a fully stable API!), this simply isn't possible.

**Comment by jswalden** [comment]
As for adding ±5dB and ±10dB relative changes -- on tip the available relative-level change choices are ±0.1dB, ±1dB, ±3dB, ±6dB.

I believe the only one in the version that Companion ships with is ±1dB, which makes sense because that's the only relative level-change operation supported at the MIDI protocol level.  The others are simply absolute-level-sets applied to whatever level Companion _thinks_ a signal is at (based on what the SQ tells the module has happened to that level previously).

To the extent relative level changes should be exposed, it would probably make more sense to stop adding discrete options and instead add an option with a user-customizable text field (and use an upgrade script to rewrite uses of the old option/choices to the new one).
